### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R#2]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R/blob/7a52a5d6615088e50a4ba11ee25524cadab8b46d/R/accessibility.R#L79

this should be unreachable due to the conditional tests in lines 65-76.

**Comment by MartijnKoster1** [comment]
The redundant line is removed
