### ISSUE TITLE
access token in repository

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R#4]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R/blob/7a52a5d6615088e50a4ba11ee25524cadab8b46d/R/get_images.R#L1

Access tokens should be kept secret and not committed to a public repo. Please go to your mapillary API key management webpage, delete this one and make a new one. Then delete this line and arrange to have the access key loaded somehow from a resource not in the repo. Either that can be a file that is explicitly NOT kept in the repo (e.g. 'api.key' or with a filename provided as an option), on the command line, from the environment variables, or make it possible to do any of the above, to give users the maximum convenience.

If you go with something like 'api.key' it is handy to add that name (or a wildcard like *.key) to the .gitignore file.

**Comment by MartijnKoster1** [comment]
Get images is removed from the repository
