### ISSUE TITLE
thumbnail size

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R#5]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R/blob/7a52a5d6615088e50a4ba11ee25524cadab8b46d/R/get_images.R#L52

Note that there is a thumb_original_url feature that gives you the original image back, this seems like it would be a bit nicer to have?

**Comment by MartijnKoster1** [comment]
The get_images.R file is removed from the repository
