### ISSUE TITLE
Hacky way to do year comparison

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R#7]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenExp_R/blob/7a52a5d6615088e50a4ba11ee25524cadab8b46d/R/green_cover.R#L288

It would be better to extract the year from the `date_time` and then compare it to the `year` variable, rather than crudely construct a timestamp for midnight of Jan 1st of that year.

**Comment by MartijnKoster1** [comment]
used lubridate now
